### ISSUE TITLE
Update to current modules

### ISSUE THREAD

**Issue by dasher** [DavidStodolsky/myturnb#3]
You can pull and merge https://github.com/dasher/myturnb/commit/a3646f7f385941921db6db29903adbe841aa320d to bring the app up to the current module versions.

I'll generate a proper pull request a little later.
##

**Comment by dasher** [comment]
I'm happy to do some cleanup on the project, remove some duplication and refactor the server side code to make it a little cleaner.

Lemme know if you're happy with these types of changes.

**Comment by DavidStodolsky** [comment]
Did you generate a proper pull request?

**Comment by dasher** [comment]
Pull request should now be visible - should be a clean merge

Next steps - I was thinking of: 
  reworking api.js as server.js to remove duplication
  add tests
  cleanup the messageDispatcher to the latest spec of socket.io

**Comment by DavidStodolsky** [comment]
> I'm happy to do some cleanup on the project, remove some duplication and refactor the server side code to make it a little cleaner.

I am trying to avoid looking at code as much as possible. If you can remove duplication, etc. to make the code easier to deal with and less likely to have bugs, fine.

By the way, you ought to subscribe to the mailing list so you get project news and can ask any questions you may have:
Mturn@googlegroups.com

**Comment by dasher** [comment]
subscribed.
I'll setup a server for you to access the current code - would you send an email to dasher@crucialdivide.com and once it's up I'll email you access details.
